function [RB] = addComponents2Panel_Structure(parent, data)

txt = data.uniqStruct;
nR = length(txt);

hCell = 1/(nR+1);
yP = hCell*nR:-hCell:0;

% cells
for iR = 1:nR+1
    hET(iR) = uipanel('parent', parent,...
                                'Unit', 'Normalized',...
                                'Position', [0.1 yP(iR) 0.8 hCell],...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'w',...
                                'ShadowColor',            'k');
end

% fill table
txt(2:nR+1) = txt;
txt{1} = 'Structures';
CLR = rand(100, 3);
CLR(2:4, :) = eye(3);
CLR(5:7, :) = 1-eye(3);
CLR(8, :) = 1;

for iR = 1:nR+1
    hRB(iR) = uicontrol('parent', hET(iR), ...
                                'Style', 'Radiobutton',...
                                'Unit', 'Normalized',...
                                'Position', [0 0 1 1], ...
                                'HorizontalAlignment', 'Center',...
                                'String', txt{iR},...
                                'Value', 1, ...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', CLR(iR, :),...
                                'Visible', 'on', ...
                                'Callback', @Callback_Radiobutton_StructurePanel);
end

hRB(1).ForegroundColor = 'c';

RB.hRB = hRB;
RB.CLR = CLR;