 function Comp = addComponents2Panel_Go(hPanel)

Comp.Pushbutton.Go = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Go',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.75 0.6 0.2], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_Go_GoPanel);

Comp.Pushbutton.Cluster = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Cluster',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.5 0.6 0.2], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_Cluster_GoPanel);

Comp.Pushbutton.Blank = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', '',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.25 0.6 0.2], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on');