function Comp = addComponents2Panel_LoadData(hPanel)

Comp.Pushbutton.hLoadData = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load Data',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.6 0.6 0.3], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_LoadData_LoadDataPanel);

Comp.Pushbutton.hCluster = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Cluster',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.1 0.6 0.3], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_Cluster_LoadDataPanel);
