function [hRB] = addComponents2Panel_Objective(parent, data)

txt = data.uniqMetric;
nR = length(txt);

hCell = 1/(nR+1);
yP = hCell*nR:-hCell:0;

% cells
for iR = 1:nR+1
    hET(iR) = uipanel('parent', parent,...
                                'Unit', 'Normalized',...
                                'Position', [0.05 yP(iR) 0.9 hCell],...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'w',...
                                'ShadowColor',            'k');
end

% fill table
txt(2:nR+1) = txt;
txt{1} = 'Objectives';
for iR = 1:nR+1
    hRB(iR) = uicontrol('parent', hET(iR), ...
                                'Style', 'Radiobutton',...
                                'Unit', 'Normalized',...
                                'Position', [0 0 1 1], ...
                                'HorizontalAlignment', 'Center',...
                                'String', txt{iR},...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'w',...
                                'Visible', 'on',...
                                'Callback', @Callback_Radiobutton_ObjectivePanel);
end

hRB(1).Enable = 'off';
hRB(1).ForegroundColor = 'c';